name: Check Project
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -  name: Checkout
         uses: actions/checkout@v3
      -  name: Install
         run: ci
      -  name: Lint
         run: npm run lint